CREATE TABLE Users (
    UserID VARCHAR(50) PRIMARY KEY,
    Email VARCHAR(255) UNIQUE NOT NULL, -- Changed from TEXT to VARCHAR with specified length
    Username VARCHAR(30) UNIQUE NOT NULL,
    Password VARCHAR(30) NOT NULL,
    Created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    Last_active DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Conversations (
    ConversationID VARCHAR(50) PRIMARY KEY,
    Created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    Last_update DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Participants (
    UserID VARCHAR(50) NOT NULL, -- Changed from NULL to NOT NULL for primary key constraint
    ConversationID VARCHAR(50) NOT NULL,
    Joined_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (UserID, ConversationID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (ConversationID) REFERENCES Conversations(ConversationID) ON DELETE CASCADE
);

CREATE TABLE Messages (
    MessageID VARCHAR(50) PRIMARY KEY,
    ConversationID VARCHAR(50) NOT NULL,
    UserID VARCHAR(50) NOT NULL,
    Delivered_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    Content TEXT DEFAULT NULL,
    FOREIGN KEY (ConversationID) REFERENCES Conversations(ConversationID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE Friends (
    UserID_1 VARCHAR(50) NOT NULL,
    UserID_2 VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    Created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (UserID_1, UserID_2),
    FOREIGN KEY (UserID_1) REFERENCES Users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (UserID_2) REFERENCES Users(UserID) ON DELETE CASCADE
);
